site_name: "laplax"
site_url: "https://laplax-org.github.io/laplax/"
repo_url: "https://github.com/laplax-org/laplax"
repo_name: "laplax-org/laplax"
# strict: false

theme:
  name: "material"
  logo: "images/laplax_logo_white.svg"
  icon:
    repo: fontawesome/brands/github # Github logo
  font:
    text: Fira Sans
  features:
    - navigation.sections
    - navigation.top
    # - toc.integrate # Show table of contents on the left
    - header.autohide # Hide the header when scrolling down
  palette:
    scheme: default
    primary: teal
    accent: cyan
    toggle:
      icon: material/eye
      name: Switch to dark mode



nav:
  - Home: index.md
  - Background: background.md
  - Design Philosophy: design_philosophy.md
  - Examples:
    - Tiny example: examples/0000_tiny_laplax.ipynb
    - Laplax for regression: examples/0001_laplax_for_regression.ipynb
    - Laplax on MNIST: examples/0002_laplax_on_mnist.ipynb
  - API Reference:
    - Overview: api.md
    - Modules:
      - laplax.api: reference/main_api.md
      - laplax.curv:
        - Overview: reference/curv.md
        - laplax.curv.ggn: reference/curv/ggn.md
        - laplax.curv.hessian: reference/curv/hessian.md
        - laplax.curv.full: reference/curv/full.md
        - laplax.curv.diagonal: reference/curv/diagonal.md
        - laplax.curv.low_rank: reference/curv/low_rank.md
        - laplax.curv.lanczos: reference/curv/lanczos.md
        - laplax.curv.lobpcg: reference/curv/lobpcg.md
        - laplax.curv.cov: reference/curv/cov.md
        - laplax.curv.utils: reference/curv/utils.md
      - laplax.eval:
        - Overview: reference/eval.md
        - "laplax.eval.pushforward": reference/eval/pushforward.md
        - laplax.eval.predictives: reference/eval/predictives.md
        - laplax.eval.likelihood: reference/eval/likelihood.md
        - laplax.eval.calibrate: reference/eval/calibrate.md
        - laplax.eval.metrics: reference/eval/metrics.md
        - laplax.eval.utils: reference/eval/utils.md
      - laplax.util:
        - Overview: reference/util.md
        - laplax.util.flatten: reference/util/flatten.md
        - laplax.util.loader: reference/util/loader.md
        - laplax.util.mv: reference/util/mv.md
        - laplax.util.ops: reference/util/ops.md
        - laplax.util.tree: reference/util/tree.md
        - laplax.util.utils: reference/util/utils.md
      - Additional:
        - laplax.enums: reference/enums.md
        - laplax.register: reference/register.md

plugins:
  - search
  - autorefs
  - bibtex:
      bib_file: docs/references.bib
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            show_source: true
            members_order: source
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_style: "google"
            extra:
              heading_level: 3
              filters: ["!^_"]
              docstring_section_style: "list"
  - mknotebooks:
      execute: false
      write_markdown: true
      enable_default_jupyter_cell_styling: true
  - gen-files:
      scripts:
        - docs/gen_api.py

markdown_extensions:
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.details

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/hide-site-name.css
  - css/custom.css
