name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
      - name: Install documentation dependencies
        run: make install-docs

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
